CREATE TABLE Exam(
ExamID			INT				IDENTITY(1,1),
SubjectID		INT				NOT NULL,
Level			INT				NOT NULL,
GradingType		NVarChar(100)	NOT NULL,
-- PK
CONSTRAINT		EXAM_PK			PRIMARY KEY(ExamID),
-- FK
CONSTRAINT		SUBJECT_FK		FOREIGN KEY(SubjectID)
				REFERENCES Exam(ExamID)
);