CREATE TABLE Written(
ExamID				INT					NOT NULL,
ExaminationTime		Decimal(3,2)		NOT NULL,
Aids				NVarChar(500)		NOT NULL,
-- PK
CONSTRAINT			WRITTEN_PK			PRIMARY KEY(ExamID),
-- FK
CONSTRAINT			WRITTEN_FK			FOREIGN KEY(ExamID)
					REFERENCES Exam(ExamID)
);