CREATE TABLE KLINIK(
	KlinikId		INT					Identity(1,1),
	Navn			NVarChar(Max)		NOT NULL,
	AdresseID		INT					NOT NULL,
	-- PK
	CONSTRAINT		KLINIK_PK			PRIMARY KEY(KlinikId),
	-- FK
	CONSTRAINT		KLINIK_ADRESSE_FK	FOREIGN KEY(AdresseID)
					REFERENCES ADRESSE(AdresseID)
					ON UPDATE CASCADE
					ON DELETE NO ACTION
);


CREATE TABLE LÆGE(
	LægeId				INT					IDENTITY(1,1),
	Navn				NVarChar(Max)		NOT NULL,
	AdresseID			INT					NOT NULL,
	KlinikId			INT					NOT NULL,
	LønId				Char(1)				NOT NULL,
	-- PK
	CONSTRAINT			LÆGE_PK				PRIMARY KEY(LægeId),
	-- FK
	CONSTRAINT			KLINIK_FK			FOREIGN KEY(KlinikId)
						REFERENCES KLINIK(KlinikId)
						ON UPDATE NO ACTION 
						ON DELETE NO ACTION,

	CONSTRAINT			LØN_FK				FOREIGN KEY(LønId)
						REFERENCES LØNRAMME(LønID)
						ON UPDATE CASCADE
						ON DELETE NO ACTION,

	CONSTRAINT			LÆGE_ADRESSE_FK		FOREIGN KEY(AdresseId)
						REFERENCES ADRESSE(AdresseID)
						ON UPDATE NO ACTION
						ON DELETE NO ACTION,
);


CREATE TABLE PATIENT(
	PatientId			INT					IDENTITY(1,1),
	Navn				NVarChar(Max)		NOT NULL,
	AdresseId			INT					NOT NULL,
	LægeId				INT					NOT NULL,
	-- PK
	CONSTRAINT			PATIENT_PK			PRIMARY KEY(PatientId),
	-- FK
	CONSTRAINT			PATIENTADRESS_FK	FOREIGN KEY(AdresseId)
						REFERENCES ADRESSE(AdresseID)
						ON UPDATE CASCADE
						ON DELETE NO ACTION,

	CONSTRAINT			LÆGE_FK				FOREIGN KEY(LægeId)
						REFERENCES LÆGE(LægeId)
						ON UPDATE CASCADE
						ON DELETE NO ACTION,
);

CREATE TABLE PÅRØRERENDE(
	PårørerendeId		INT					IDENTITY(1,1),
	Navn				NVarChar(Max)		NOT NULL,
	AdresseId			INT					NOT NULL,
	-- PK
	CONSTRAINT			PÅ_PK				PRIMARY KEY(PårørerendeId),
	-- FK
	CONSTRAINT			P_ADRESS_FK			FOREIGN KEY(AdresseId)
						REFERENCES ADRESSE(AdresseID)
						ON UPDATE CASCADE
						ON DELETE NO ACTION
);

CREATE TABLE PATIENTPÅRØRENDE(
	PatientPårørende	INT				NOT NULL,
	PatientId			INT				NOT NULL,
	PårørendeId			INT				NOT NULL,
	-- PK
	CONSTRAINT			PP_FK			PRIMARY KEY(PatientPårørende),
	-- FK
	CONSTRAINT			PÅ_FK			FOREIGN KEY(PårørendeId)
						REFERENCES PÅRØRERENDE(PårørerendeId)
						ON UPDATE CASCADE
						ON DELETE NO ACTION,

	CONSTRAINT			PA_FK			FOREIGN KEY(PatientId)
						REFERENCES PATIENT(PatientId)
						ON UPDATE NO ACTION
						ON DELETE NO ACTION,
);

CREATE TABLE AFTALE(
	AftaleID			INT				IDENTITY(1,1),
	PatientPårørende	INT				NOT NULL,
	LægeId				INT				NOT NULL,
	Dato				DateTime2		NOT NULL,
	-- PK
	CONSTRAINT			AFTALE_PK		PRIMARY KEY(AftaleID),
	-- FK
	CONSTRAINT			PP_FKK			FOREIGN KEY(PatientPårørende)
						REFERENCES PATIENTPÅRØRENDE(PatientPårørende),

	CONSTRAINT			LÆGE2_FK			FOREIGN KEY(LægeId)
						REFERENCES LÆGE(LægeId)
						ON UPDATE CASCADE
						ON DELETE NO ACTION
);

