CREATE TABLE ORDERS(
OrderID			INT			IDENTITY(1,1),
Date			Date		NOT NULL,
Amount			INT			NOT NULL,
PackID			INT			NOT NULL,
-- PK
CONSTRAINT		ORDER_PK	PRIMARY KEY(OrderID),
-- FK
CONSTRAINT		PACKING_FK	FOREIGN KEY(PackID)
				REFERENCES	Packaging(PackID)
);