CREATE TABLE Tractor(
VIN				NVarChar(50)	NOT NULL,
Horsepower		INT				NULL,
-- PK
CONSTRAINT		TractorPK		PRIMARY KEY (VIN),
-- FK
CONSTRAINT		TractorFK		FOREIGN KEY(VIN)
				REFERENCES Machine(VIN)
);


CREATE TABLE Harvester(
VIN				NVarChar(50)	NOT NULL,
Performance		Decimal(5, 2)	NULL,
--
CONSTRAINT		HARVESTER_PK	PRIMARY KEY(VIN),
CONSTRAINT		HarvesterFK		FOREIGN KEY(VIN)
				REFERENCES	Machine(VIN)
);

CREATE TABLE Plow(
VIN				NVarChar(50)	NOT NULL,
NoOfChisels		int				NULL,
--
CONSTRAINT		PLOW_PK			PRIMARY KEY(VIN),
CONSTRAINT		PLOW_FK			FOREIGN KEY(VIN)
				REFERENCES	Machine(VIN)
);