CREATE TABLE Timesheet_Task(
SheetID		INT			 NOT NULL,
TaskID		INT			 NOT NULL,
-- PK
CONSTRAINT	TIMETASK_PK	PRIMARY KEY(SheetID, TaskID),
-- FK
CONSTRAINT SHEET_FK		FOREIGN KEY(SheetID)
			REFERENCES TimeSheet(SheetID),
CONSTRAINT TASK_FK		FOREIGN KEY(TaskID)
			REFERENCES Task(TaskID)
);